framework:
    workflows:
        thread_support:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'

            supports:
                - App\Entity\Forum\Thread

            places: !php/enum App\Enums\ThreadStatusEnum

            transitions:

                # El hilo pasa de abierto a revisión
                review:
                    from: !php/enum App\Enums\ThreadStatusEnum::OPEN
                    to: !php/enum App\Enums\ThreadStatusEnum::IN_REVIEW

                # El staff responde → espera al cliente
                staff_reply:
                    from:
                        - !php/enum App\Enums\ThreadStatusEnum::IN_REVIEW
                        - !php/enum App\Enums\ThreadStatusEnum::WAITING_SUPPORT
                        - !php/enum App\Enums\ThreadStatusEnum::RESOLVED
                    to: !php/enum App\Enums\ThreadStatusEnum::WAITING_CUSTOMER

                # El cliente responde → espera al staff
                customer_reply:
                    from:
                        - !php/enum App\Enums\ThreadStatusEnum::WAITING_CUSTOMER
                        - !php/enum App\Enums\ThreadStatusEnum::RESOLVED
                    to: !php/enum App\Enums\ThreadStatusEnum::WAITING_SUPPORT

                # El hilo se marca como resuelto (staff o usuario)
                resolve:
                    from:
                        - !php/enum App\Enums\ThreadStatusEnum::OPEN
                        - !php/enum App\Enums\ThreadStatusEnum::IN_REVIEW
                        - !php/enum App\Enums\ThreadStatusEnum::WAITING_CUSTOMER
                        - !php/enum App\Enums\ThreadStatusEnum::WAITING_SUPPORT
                    to: !php/enum App\Enums\ThreadStatusEnum::RESOLVED

                # Cierre definitivo (no hay vuelta atrás)
                close:
                    from:
                        - !php/enum App\Enums\ThreadStatusEnum::OPEN
                        - !php/enum App\Enums\ThreadStatusEnum::IN_REVIEW
                        - !php/enum App\Enums\ThreadStatusEnum::WAITING_CUSTOMER
                        - !php/enum App\Enums\ThreadStatusEnum::WAITING_SUPPORT
                        - !php/enum App\Enums\ThreadStatusEnum::RESOLVED
                    to: !php/enum App\Enums\ThreadStatusEnum::CLOSED
