name: pfc

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${DATABASE_VERSION_NUMBER}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: mysqladmin ping
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - database_data:/var/lib/mysql
    secrets:
      - db_password
  ###< doctrine/doctrine-bundle ###

  webserver:
    image: idmarinas/pfc:${APP_VERSION}
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    environment:
      SERVER_NAME: ${APP_SERVER_NAME}
      CLOUDFLARE_API_TOKEN_FILE: /run/secrets/cloudflare_api_token
    volumes:
      # Named volumes for /data and /config to persist important information.
      - caddy_data:/data
      - caddy_config:/config
    secrets:
      - cloudflare_api_token
    tty: true
    depends_on:
      - database

  messenger_worker_async:
    image: idmarinas/pfc:${APP_VERSION}
    entrypoint: '/usr/local/bin/msn_async_entrypoint.sh'
    restart: always
    healthcheck:
      test: [ "CMD", "php", "bin/console", "about" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - database
    volumes:
      - scheduler_cache:/app/var/scheduler
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M


  messenger_worker_scheduler:
    image: idmarinas/pfc:${APP_VERSION}
    entrypoint: '/usr/local/bin/msn_scheduler_entrypoint.sh'
    restart: always
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

volumes:
  caddy_data:
  caddy_config:
  scheduler_cache:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###

secrets:
  db_password:
    environment: DATABASE_PASSWORD
  cloudflare_api_token:
    environment: CLOUDFLARE_API_TOKEN
