services:
  ###> doctrine/doctrine-bundle ###
  database:
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}_dev
      MYSQL_USER: ${DATABASE_USER}_dev
    volumes:
      - database_data_dev:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###

  database_test:
    restart: on-failure
    extends:
      file: compose.yaml
      service: database
    ports: !reset [ ]
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}_test
      MYSQL_USER: ${DATABASE_USER}_test
    volumes:
      - database_data_test:/var/lib/mysql

  webserver:
    restart: on-failure
    image: idmarinas/pfc:${APP_VERSION}-dev
    volumes:
      - ./:/app
      ## SSH
      - ssh_key:/root/.ssh
    depends_on: !override
      - database
      - database_test
      - mailer

  ###> symfony/mailer ###
  mailer:
    restart: on-failure
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

volumes:
  database_data_dev:
  database_data_test:
  ssh_key:
    external: true
