services:
  database:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 5s

  webserver:
    restart: always
    volumes:
      # Shared files between deployments
      - source_uploads:/app/public/uploads # For example, files uploaded by users
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 5s

volumes:
  source_uploads:
