# Main WebSite
<VirtualHost *:443>
	ServerName localhost
	#UseCanonicalName Off

	ErrorLog /usr/local/apache2/logs/error-ssl.log
	CustomLog /usr/local/apache2/logs/access-ssl.log combined

	Include conf/x/common.conf
	Include conf/x/dev-certs.conf
</VirtualHost>
