# Main WebSite
<VirtualHost *:443>
	ServerName localhost
	ServeAlias www.localhost
	#UseCanonicalName Off

	ErrorLog /usr/local/apache2/logs/error-ssl.log
	CustomLog /usr/local/apache2/logs/access-ssl.log combined

	Include conf/x/common.conf
	Include conf/x/prod-certs.conf

	<IfModule mod_rewrite.c>
		RewriteEngine On
		# Add the www in front if they have not been added
    RewriteCond %{HTTP_HOST} !^www\. [NC]
    RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]
	</IfModule>
</VirtualHost>
