# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: ../src/Controller/*
    type: attribute
    name_prefix: app_
    exclude:
        - ../src/Controller/Admin/
        - ../src/Controller/User/
        - ../src/Controller/Forum/

easyadmin:
    resource: .
    type: easyadmin.routes

admin:
    resource: ../src/Controller/Admin/
    type: attribute
    prefix: '/%app.route_prefix.admin%'
    name_prefix: admin_

user:
    resource: ../src/Controller/User/
    type: attribute
    prefix: /user
    name_prefix: app_user_

forum:
    resource: ../src/Controller/Forum/
    type: attribute
    prefix: /forums
    name_prefix: app_forums_
